### ISSUE TITLE
goroutine cocurrent issue

### ISSUE THREAD

**Issue by gatspy** [dmitryburov/gorm-paginator#1]
getCounts func the db must use session.

[fatal error: concurrent map writes](https://github.com/go-gorm/gorm/issues/3126)

```go
db = db.Session(&gorm.Session{
    WithConditions: true,
})
```

**Comment by dmitryburov** [comment]
> getCounts func the db must use session.
Why? 
No problem method, see result: https://prnt.sc/vkzpko, https://prnt.sc/vkzpko
What is your problem?

**Comment by gatspy** [comment]
@dmitryburov Uncomment example code on the 71 line, and modify it , then run it.
```go
dbEntity = dbEntity.Where("id = ?", 1)
```

#### fatal error

```go
API server listening at: 127.0.0.1:33851
fatal error: concurrent map read and map write

goroutine 27 [running]:
runtime.throw(0x16115b9, 0x21)
    /usr/local/var/goenv/versions/1.15.3/src/runtime/panic.go:1116 +0x72 fp=0xc000193bf0 sp=0xc000193bc0 pc=0x103ebd2
runtime.mapaccess1_faststr(0x159c320, 0xc0000aaba0, 0x1605769, 0x5, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/runtime/map_faststr.go:21 +0x771 fp=0xc000193c90 sp=0xc000193bf0 pc=0x1018f71
gorm.io/gorm.(*Statement).AddClause(0xc0000c11e0, 0x1657280, 0xc0000b67a0)
    /Users/gl/Projects/golang/vendor/pkg/mod/gorm.io/gorm@v1.20.7/statement.go:227 +0x16f fp=0xc000193d30 sp=0xc000193c90 pc=0x14c6b6f
gorm.io/gorm.SoftDeleteQueryClause.ModifyStatement(0xc0000c09c0, 0xc0000c11e0)
    /Users/gl/Projects/golang/vendor/pkg/mod/gorm.io/gorm@v1.20.7/soft_delete.go:80 +0x76a fp=0xc000193fe8 sp=0xc000193d30 pc=0x14c260a
gorm.io/gorm.(*Statement).AddClause(0xc0000c11e0, 0x1656f80, 0xc0000c09c0)
    /Users/gl/Projects/golang/vendor/pkg/mod/gorm.io/gorm@v1.20.7/statement.go:224 +0xd7 fp=0xc000194088 sp=0xc000193fe8 pc=0x14c6ad7
gorm.io/gorm/callbacks.BuildQuerySQL(0xc0000aab70)
    /Users/gl/Projects/golang/vendor/pkg/mod/gorm.io/gorm@v1.20.7/callbacks/query.go:34 +0x19b fp=0xc0001950a0 sp=0xc000194088 pc=0x1533dfb
gorm.io/gorm/callbacks.Query(0xc0000aab70)
    /Users/gl/Projects/golang/vendor/pkg/mod/gorm.io/gorm@v1.20.7/callbacks/query.go:16 +0x6e fp=0xc0001951e0 sp=0xc0001950a0 pc=0x153398e
gorm.io/gorm.(*processor).Execute(0xc000206780, 0xc0000aab70)
    /Users/gl/Projects/golang/vendor/pkg/mod/gorm.io/gorm@v1.20.7/callbacks.go:105 +0x5d4 fp=0xc0001953c8 sp=0xc0001951e0 pc=0x14a9ed4
gorm.io/gorm.(*DB).Find(0xc0000aab70, 0x156ec40, 0xc0000b6720, 0x0, 0x0, 0x0, 0xc0000aab70)
    /Users/gl/Projects/golang/vendor/pkg/mod/gorm.io/gorm@v1.20.7/finisher_api.go:138 +0x285 fp=0xc0001954a8 sp=0xc0001953c8 pc=0x14b1aa5
github.com/dmitryburov/gorm-paginator.Pages(0xc000195710, 0x156ec40, 0xc0000b6720, 0x0, 0x0, 0x0)
    /Users/gl/Projects/golang/vendor/pkg/mod/github.com/dmitryburov/gorm-paginator@v0.9.5/paginator.go:75 +0x3d9 fp=0xc000195600 sp=0xc0001954a8 pc=0x14da079
main.getBookList(0x1656bc0, 0xc0000e40e0, 0xc000234200)
    /Users/gl/Projects/golang/work/paginator/main.go:74 +0x67a fp=0xc000195810 sp=0xc000195600 pc=0x154e47a
net/http.HandlerFunc.ServeHTTP(0x1623118, 0x1656bc0, 0xc0000e40e0, 0xc000234200)
    /usr/local/var/goenv/versions/1.15.3/src/net/http/server.go:2042 +0x44 fp=0xc000195838 sp=0xc000195810 pc=0x13e0244
net/http.(*ServeMux).ServeHTTP(0x185b6c0, 0x1656bc0, 0xc0000e40e0, 0xc000234200)
    /usr/local/var/goenv/versions/1.15.3/src/net/http/server.go:2417 +0x1ab fp=0xc0001958a8 sp=0xc000195838 pc=0x13e300b
net/http.serverHandler.ServeHTTP(0xc0000e4000, 0x1656bc0, 0xc0000e40e0, 0xc000234200)
    /usr/local/var/goenv/versions/1.15.3/src/net/http/server.go:2843 +0x22b fp=0xc0001958f0 sp=0xc0001958a8 pc=0x13e4d6b
net/http.(*conn).serve(0xc0002303c0, 0x16579c0, 0xc000207880)
    /usr/local/var/goenv/versions/1.15.3/src/net/http/server.go:1925 +0x1805 fp=0xc000195fc8 sp=0xc0001958f0 pc=0x13df1a5
runtime.goexit()
    /usr/local/var/goenv/versions/1.15.3/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000195fd0 sp=0xc000195fc8 pc=0x1077201
created by net/http.(*Server).Serve
    /usr/local/var/goenv/versions/1.15.3/src/net/http/server.go:2969 +0x970

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x4572278, 0x72, 0xffffffffffffffff)
    /usr/local/var/goenv/versions/1.15.3/src/runtime/netpoll.go:220 +0x65
internal/poll.(*pollDesc).wait(0xc0000b4418, 0x72, 0x1814700, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(0xc0000b4418, 0xffffffffffffff00, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/internal/poll/fd_poll_runtime.go:92 +0x45
internal/poll.(*FD).Accept(0xc0000b4400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/internal/poll/fd_unix.go:394 +0x419
net.(*netFD).accept(0xc0000b4400, 0x0, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/net/fd_unix.go:172 +0x85
net.(*TCPListener).accept(0xc0000b6700, 0x0, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/net/tcpsock_posix.go:139 +0x65
net.(*TCPListener).Accept(0xc0000b6700, 0x0, 0x0, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/net/tcpsock.go:261 +0x78
net/http.(*Server).Serve(0xc0000e4000, 0x1656940, 0xc0000b6700, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/net/http/server.go:2937 +0x42e
net/http.(*Server).ListenAndServe(0xc0000e4000, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/net/http/server.go:2866 +0x1c5
net/http.ListenAndServe(0x1605665, 0x5, 0x0, 0x0, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/net/http/server.go:3120 +0xdb
main.main()
    /Users/gl/Projects/golang/work/paginator/main.go:35 +0x186

goroutine 19 [select]:
database/sql.(*DB).connectionOpener(0xc00011f860, 0x16579c0, 0xc000207700)
    /usr/local/var/goenv/versions/1.15.3/src/database/sql/sql.go:1126 +0xf9
created by database/sql.OpenDB
    /usr/local/var/goenv/versions/1.15.3/src/database/sql/sql.go:740 +0x265

goroutine 26 [select]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc0002150e0, 0xc000150ea0, 0xc0001105a0)
    /Users/gl/Projects/golang/vendor/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:621 +0x11b
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
    /Users/gl/Projects/golang/vendor/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:618 +0xe9

goroutine 35 [IO wait]:
internal/poll.runtime_pollWait(0x45720b8, 0x72, 0x18147c8)
    /usr/local/var/goenv/versions/1.15.3/src/runtime/netpoll.go:220 +0x65
internal/poll.(*pollDesc).wait(0xc000187198, 0x72, 0xffffffffffffff00, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(0xc000187198, 0xffffffffffffff00, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/internal/poll/fd_poll_runtime.go:92 +0x45
internal/poll.(*FD).Read(0xc000187180, 0xc000232461, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/internal/poll/fd_unix.go:159 +0x3f4
net.(*netFD).Read(0xc000187180, 0xc000232461, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/net/fd_posix.go:55 +0x7c
net.(*conn).Read(0xc00013c868, 0xc000232461, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/var/goenv/versions/1.15.3/src/net/net.go:182 +0xb5
net/http.(*connReader).backgroundRead(0xc000232450)
    /usr/local/var/goenv/versions/1.15.3/src/net/http/server.go:690 +0xb7
created by net/http.(*connReader).startBackgroundRead
    /usr/local/var/goenv/versions/1.15.3/src/net/http/server.go:686 +0x13a

goroutine 36 [runnable]:
gorm.io/gorm.(*Statement).Build(0xc0000c11e0, 0xc000190f10, 0x7, 0x7)
    /Users/gl/Projects/golang/vendor/pkg/mod/gorm.io/gorm@v1.20.7/statement.go:379 +0x158
gorm.io/gorm/callbacks.BuildQuerySQL(0xc0000aab70)
    /Users/gl/Projects/golang/vendor/pkg/mod/gorm.io/gorm@v1.20.7/callbacks/query.go:163 +0x1e28
gorm.io/gorm/callbacks.Query(0xc0000aab70)
    /Users/gl/Projects/golang/vendor/pkg/mod/gorm.io/gorm@v1.20.7/callbacks/query.go:16 +0x6e
gorm.io/gorm.(*processor).Execute(0xc000206780, 0xc0000aab70)
    /Users/gl/Projects/golang/vendor/pkg/mod/gorm.io/gorm@v1.20.7/callbacks.go:105 +0x5d4
gorm.io/gorm.(*DB).Count(0xc0000aab70, 0xc0000a6338, 0xc0000aab70)
    /Users/gl/Projects/golang/vendor/pkg/mod/gorm.io/gorm@v1.20.7/finisher_api.go:378 +0x449
github.com/dmitryburov/gorm-paginator.getCounts(0xc0000aab70, 0x156ec40, 0xc0000b6720, 0xc0000a40e0, 0xc0000a6338)
    /Users/gl/Projects/golang/vendor/pkg/mod/github.com/dmitryburov/gorm-paginator@v0.9.5/paginator.go:108 +0x5c
created by github.com/dmitryburov/gorm-paginator.Pages
    /Users/gl/Projects/golang/vendor/pkg/mod/github.com/dmitryburov/gorm-paginator@v0.9.5/paginator.go:43 +0x12f
```

**Comment by dmitryburov** [comment]
> @dmitryburov Uncomment example code on the 71 line, and modify it , then run it.

It's working fine - https://prnt.sc/vn16en

```log
[2.012ms] [rows:1] SELECT * FROM `books` WHERE id = 1 AND `books`.`deleted_at` IS NULL LIMIT 20
```

Please, show your stack and actual versions.
Try using the MySQL wrapper driver - gorm.io/driver/mysql

**Comment by gatspy** [comment]
the example file only changed `where` condition. my mod file as follow.
the `paging.ShowSQL` line is set to false or commented 

```go
// show sql log if debug
// paging.ShowSQL = true

// if need conditions or more
dbEntity= dbEntity.Where("id = ?", 1)
```

```go
go 1.15

require (
	github.com/dmitryburov/gorm-paginator v0.9.5
	gorm.io/driver/mysql v1.0.3
	gorm.io/gorm v1.20.7
)
```

**Comment by dmitryburov** [comment]
@gatspy, please, show code paginator/main.go

**Comment by dmitryburov** [comment]
@gatspy, you are using gorm.io/gorm v1.20.7 ?
v1.20.6 - no problem (try again)
bad v1.20.7...it's true

**Comment by gatspy** [comment]
@dmitryburov thank you for your prompt reply. i have modified the `gorm` version, bus there are still problems.

### go env

```
go version go1.15.3 darwin/amd64
```

#### go.sum
```go
github.com/dmitryburov/gorm-paginator v0.9.5 h1:t0P0b4ZmoYipc2Bzr6d6vns2FKJ2Yt2ouCzvZe9WsLo=
github.com/dmitryburov/gorm-paginator v0.9.5/go.mod h1:1vA3SLI5qbiYPRYy/27JkFjfDGWER0pNwyfnAdPa+uE=
github.com/go-sql-driver/mysql v1.5.0 h1:ozyZYNQW3x3HtqT1jira07DN2PArx2v7/mN66gGcHOs=
github.com/go-sql-driver/mysql v1.5.0/go.mod h1:DCzpHaOWr8IXmIStZouvnhqoel9Qv2LBy8hT2VhHyBg=
github.com/jinzhu/inflection v1.0.0 h1:K317FqzuhWc8YvSVlFMCCUb36O/S9MCKRDI7QkRKD/E=
github.com/jinzhu/inflection v1.0.0/go.mod h1:h+uFLlag+Qp1Va5pdKtLDYj+kHp5pxUVkryuEj+Srlc=
github.com/jinzhu/now v1.1.1 h1:g39TucaRWyV3dwDO++eEc6qf8TVIQ/Da48WmqjZ3i7E=
github.com/jinzhu/now v1.1.1/go.mod h1:d3SSVoowX0Lcu0IBviAWJpolVfI5UJVZZ7cO71lE/z8=
gorm.io/driver/mysql v1.0.3 h1:+JKBYPfn1tygR1/of/Fh2T8iwuVwzt+PEJmKaXzMQXg=
gorm.io/driver/mysql v1.0.3/go.mod h1:twGxftLBlFgNVNakL7F+P/x9oYqoymG3YYT8cAfI9oI=
gorm.io/gorm v1.20.0/go.mod h1:0HFTzE/SqkGTzK6TlDPPQbAYCluiVvhzoA1+aVyzenw=
gorm.io/gorm v1.20.4/go.mod h1:0HFTzE/SqkGTzK6TlDPPQbAYCluiVvhzoA1+aVyzenw=
gorm.io/gorm v1.20.6 h1:qa7tC1WcU+DBI/ZKMxvXy1FcrlGsvxlaKufHrT2qQ08=
gorm.io/gorm v1.20.6/go.mod h1:0HFTzE/SqkGTzK6TlDPPQbAYCluiVvhzoA1+aVyzenw=
```

#### main.go
```go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strconv"

	paginator "github.com/dmitryburov/gorm-paginator"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

var (
	db *gorm.DB
	// see https://gorm.io/docs/connecting_to_the_database.html
	dbConn = "root:123456@@tcp(localhost:3306)/test?parseTime=True"
)

type Book struct {
	gorm.Model
	Title string
}

func main() {

	var err error

	if err = initDatabase(); err != nil {
		log.Fatal("Error init database: ", err)
	}

	http.HandleFunc("/", getBookList)
	err = http.ListenAndServe(":9000", nil)
	if err != nil {
		log.Fatal("Error serve: ", err)
	}

}

func getBookList(w http.ResponseWriter, r *http.Request) {

	var (
		err      error
		query    = r.URL.Query()
		dbEntity = db
		paging   = paginator.Paging{}
		bookList = struct {
			Items      []*Book               `json:"items"`
			Pagination *paginator.Pagination `json:"pagination"`
		}{}
	)

	// get paging params from query
	if len(query.Get("page")) > 0 && query.Get("page") != "" {
		paging.Page, _ = strconv.Atoi(query.Get("page"))
	}
	if len(query.Get("limit")) > 0 && query.Get("limit") != "" {
		paging.Limit, _ = strconv.Atoi(query.Get("limit"))
	}
	if orders, ok := query["order"]; ok || len(orders) > 0 {
		for i := range orders {
			paging.OrderBy = append(paging.OrderBy, orders[i])
		}
	}
	// show sql log if debug
	// paging.ShowSQL = true

	// if need conditions or more
	dbEntity = dbEntity.Where("id = ?", 1)
	// dbEntity = db.Session(&gorm.Session{})
	// get data with pagination
	bookList.Pagination, err = paginator.Pages(&paginator.Param{
		DB:     dbEntity,
		Paging: &paging,
	}, &bookList.Items)
	if err != nil {
		log.Fatal("Error get list: ", err.Error())
	}

	// if empty list
	//if bookList.Pagination.IsEmpty() {
	//
	//}

	w.Header().Set("Content-Type", "application/json")
	err = json.NewEncoder(w).Encode(bookList)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	return
}

func initDatabase() (err error) {

	db, err = gorm.Open(mysql.Open(dbConn), &gorm.Config{})
	if err == nil {

		if !db.Migrator().HasTable(&Book{}) {
			fmt.Println("Start migrate")

			err = db.Migrator().CreateTable(&Book{})
			if err != nil {
				return
			}

			books := []Book{
				{Title: "Green mile"},
				{Title: "The Hobbit"},
				{Title: "The Da Vinci Code"},
				{Title: "Angels & Demons"},
				{Title: "Harry Potter"},
				{Title: "The Ginger Man"},
				{Title: "Cosmos"},
				{Title: "Angels & Demons"},
				{Title: "The Godfather"},
				{Title: "Dune"},
			}

			err = db.Create(&books).Error
			if err != nil {
				return
			}

			fmt.Println("Migrate success!")
		}
	}

	return
}
```

#### error

```
~/Projects/golang/vendor/pkg/mod/github.com/dmitryburov/gorm-paginator@v0.9.5/paginator.go:75 Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT count(1) FROM `books` WHERE id = ? AND `books`.`deleted_at` IS NULL AND `' at line 1
[42.993ms] [rows:0] SELECT count(1) FROM `books` WHERE id = SELECT count(1) FROM `books` WHERE id = 1 AND `books`.`deleted_at` IS NULL AND `books`.`deleted_at`LIMIT 20LIMIT 20
2020/11/21 16:08:50 Error get list: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT count(1) FROM `books` WHERE id = ? AND `books`.`deleted_at` IS NULL AND `' at line 1
```
`concurrent map writes` panic happens occasionally

```
fatal error: concurrent map writes
fatal error: concurrent map writes
```

**Comment by dmitryburov** [comment]
@gatspy try adding in my paginator.go:

```go
func Pages(p *Param, result interface{}) (paginator *Pagination, err error) {

	var (
		...
		db       = p.DB.Session(&gorm.Session{})
		...
 	)
	...
}
```

it's work for me (1.20.6 and 1.20.7)

**Comment by gatspy** [comment]
that's ok .working fine, tks!
